## McEliece

A McElice cryptosystem code.

###### [Classic McEliece](https://en.wikipedia.org/wiki/McEliece_cryptosystem) in [python](https://en.wikipedia.org/wiki/Python_(programming_language)).

###### A [GPL-3.0](https://en.wikipedia.org/wiki/GNU_General_Public_License#Version_3) license

###### Advantages: 10 stars' rating.





#### Mount google drive.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
%cd drive/MyDrive/cyber quantum/mceliece/pythonMCS

/content/drive/MyDrive/cyber quantum/mceliece/pythonMCS


#### imports

In [6]:
import numpy as np
from mc_core import *

#### Crypto functions visualization

##### Functions

1.   Generate S matrix: Generates an invertable matrix k * k
2.   Generate P matrix: Generates a permutation matrix n x n using the given sequence



In [68]:
k = 4
n = 4

S = genSMatrix(k)
P = genPMatrix(n)

##### View matrices
###### View S and P.

In [67]:
S

matrix([[1, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 0]])

In [69]:
P

matrix([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

##### Mod-2
###### Visualize mod-2 operation on S and P matrices.

In [70]:
modTwo(P)

matrix([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

In [71]:
modTwo(S)

matrix([[1, 0, 0, 1],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 0, 0, 1]])

##### Bitflip
###### Flips the bit you tell it, -1 for random bit flip, 0 for no flip.
###### Visualize bitflip operation on S and P matrices.

In [73]:
n = 1

bitFlip(S, n)

matrix([[0, 0, 0, 1],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 0, 0, 1]])

In [74]:
bitFlip(P, n)

matrix([[1, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

#### McEliece cipher.

##### Create a random 10 messages.

In [44]:
n_messages = 10
dimensions = [1, 4]

messages = []
for _ in range(n_messages):
  messages.append(np.matrix(np.random.rand(dimensions[0], dimensions[1])))

##### view the messages.

In [45]:
messages

[matrix([[0.15535612, 0.71774466, 0.23720825, 0.27857838]]),
 matrix([[0.24368385, 0.27579557, 0.26064849, 0.89001012]]),
 matrix([[0.28113931, 0.9721871 , 0.85659476, 0.41036165]]),
 matrix([[0.09389356, 0.26095691, 0.97619588, 0.50200421]]),
 matrix([[0.65196944, 0.38045101, 0.19739571, 0.25764521]]),
 matrix([[0.86923157, 0.55892332, 0.6029754 , 0.68543821]]),
 matrix([[0.66210728, 0.13388189, 0.9910148 , 0.84583717]]),
 matrix([[0.81194543, 0.83953969, 0.43819819, 0.07124261]]),
 matrix([[0.33984142, 0.69441409, 0.88963041, 0.09332491]]),
 matrix([[0.9860221 , 0.45144396, 0.81823001, 0.66918332]])]

#### Generate keys.

##### Generate 10 private and public keys.

In [58]:
private_key = privateKeyH84()
public_key = publicKeyH84(private_key.makeGPrime())

##### View key object.

In [59]:
public_key

In [60]:
private_key

#### Encrypt

##### Encrypt the messages with a random mod-2 bitflips.

In [63]:
messages_encrypted = []

for index in range(n_messages):
  messages_encrypted.append(public_key.encrypt(messages[index]))

##### View encrypted messages

In [64]:
messages_encrypted

[matrix([[1.        , 0.27857838, 0.15535612, 0.51578663, 0.95495291,
          0.71774466, 0.39256437, 1.38888741]]),
 matrix([[1.40948954, 0.89001012, 0.24368385, 1.        , 0.53644406,
          0.27579557, 0.50433234, 1.67013803]]),
 matrix([[1.66368807, 0.41036165, 0.28113931, 1.        , 1.82878186,
          0.9721871 , 1.13773407, 0.52028283]]),
 matrix([[0.85685468, 0.50200421, 0.09389356, 1.47820009, 1.        ,
          0.26095691, 1.07008944, 1.83305056]]),
 matrix([[1.29006566, 0.25764521, 1.        , 0.45504092, 0.57784672,
          0.38045101, 0.84936516, 1.48746137]]),
 matrix([[0.11359309, 0.68543821, 0.86923157, 1.28841361, 1.16189872,
          0.55892332, 1.        , 0.7165685 ]]),
 matrix([[1.64182633, 0.84583717, 0.66210728, 1.83685197, 1.12489669,
          0.13388189, 1.        , 0.63284114]]),
 matrix([[1.72272774, 0.07124261, 0.81194543, 0.5094408 , 1.        ,
          0.83953969, 1.25014363, 0.16092593]]),
 matrix([[1.12758042, 0.09332491, 0.33984142, 0.

#### Decrypt
##### Decrypt messages using mod-2 bitflips.

In [65]:
messages_decrypted = []

for index in range(n_messages):
  messages_decrypted.append(private_key.decrypt(messages_encrypted[index]))

##### View decrypted messages

In [54]:
messages_decrypted

[matrix([[1.17957545, 1.74931792, 0.79436501, 0.27857838]]),
 matrix([[0.87661246, 0.5771128 , 0.04066874, 0.89001012]]),
 matrix([[0.91646159, 1.50609993, 1.67731807, 0.41036165]]),
 matrix([[0.57621598, 1.21735709, 1.9802043 , 0.50200421]]),
 matrix([[0.83824372, 1.29053285, 0.71268613, 0.25764521]]),
 matrix([[1.93478185, 1.13575055, 1.97385183, 0.68543821]]),
 matrix([[0.44941216, 1.80758583, 0.83685197, 1.        ]]),
 matrix([[0.14295084, 0.34898049, 1.07124261, 0.07124261]]),
 matrix([[1.89827475, 0.67736941, 1.09332491, 0.09332491]]),
 matrix([[0.53291999, 1.42627062, 0.48741333, 1.        ]])]

##### There is an error on the private key's decryption.

